---
title: "Memorial circunstanciado para concurso de Professor Doutor junto ao Departamento de Bioquímica"
author: 
  - name: "Dr. Marcel Rodrigues Ferreira"
    id: "MRF"
    email: marcel.ferreira@unesp.br
    affiliation: 
      - name: UNESP
        city: Botucatu
        state: SP
        url: https://www2.unesp.br/
format: 
  typst:
    keep-typ: true
    toc: true
    citeproc: true
    section-numbering: 1.1.a
    toc-title: "Índice"
    include-in-header:
        - text: |
            /* Color links */
            #show link: set text(fill: rgb(0, 0, 255))
editor: visual
date: today
lang: pt-br
bibliography: references.bib
bibliographystyle: associacao-brasileira-de-normas-tecnicas.csl
---

```{=typst}
#pagebreak()
```
## Apresentação {#sec-1}

Ao longo da minha trajetória acadêmica, alguns acontecimentos foram particularmente marcantes e contribuíram de forma decisiva para a construção da minha identidade como pesquisador e educador. Entre eles, destaco a conclusão do ensino médio, o ingresso no curso de [Física Médica](https://www.ibb.unesp.br/#!/ensino/graduacao/curso/fisica-medica/) na Universidade Estadual Paulista "Júlio de Mesquita Filho" ([UNESP](https://www2.unesp.br/)), o desenvolvimento das atividades de iniciação científica, a defesa da dissertação de mestrado e da tese de doutorado, bem como o início das atividades de pós-doutorado. Esses momentos, mais do que marcos formais, representaram etapas fundamentais de reflexão, amadurecimento e definição de objetivos acadêmicos e profissionais.

Embora tais conquistas sejam, frequentemente, associadas a celebrações, sempre as compreendi como oportunidades de análise crítica da própria trajetória, permitindo ajustes de rota e o delineamento de novos objetivos. Mesmo diante dos desafios e das incertezas inerentes à carreira acadêmica, mantive de forma consistente o propósito de me tornar professor universitário em regime de dedicação integral ao ensino, à pesquisa e à formação de recursos humanos, entendendo a universidade pública como espaço privilegiado de produção de conhecimento, inclusão e transformação social.

Minha formação científica foi construída em ambientes interdisciplinares, com forte integração entre ciências básicas, biologia molecular, bioinformática e ciência dos biomateriais, possibilitando uma atuação científica que transita entre abordagens experimentais e computacionais. Ao longo desse percurso, busquei consolidar uma base sólida em pesquisa, ampliar redes de colaboração nacionais e internacionais e desenvolver competências didáticas voltadas à formação crítica de estudantes de graduação e pós-graduação.

O presente memorial tem como objetivo apresentar uma análise circunstanciada da minha trajetória acadêmica e profissional, no contexto de minha candidatura à carreira docente. Este documento reúne informações que não se encontram integralmente descritas em currículos ou bases públicas, oferecendo uma visão integrada das atividades desenvolvidas, das contribuições científicas realizadas e das perspectivas futuras de atuação acadêmica.

As informações pessoais relevantes estão resumidas na Seção [2](#sec-2). As Seções [3](#sec-3) e [4](#sec-4) apresentam, respectivamente, minha formação acadêmica e científica e minha atuação profissional. As seções subsequentes estão organizadas da seguinte forma: (i) Atividades Didáticas e Formação de Recursos Humanos (Seção [5](#sec-5)); (ii) Atividades de Pesquisa (Seção [6](#sec-6)); (iii) Atividades de Extensão e Serviços à Comunidade (Seção [7](#sec-7)); e (iv) Atividades Administrativas (Seção [8](#sec-8)). Na Seção [9](#sec-9) é apresentada a nomenclatura adotada para os anexos. Por fim, na Seção [10](#sec-10), apresento considerações finais, sintetizando minha trajetória e as perspectivas de desenvolvimento acadêmico.

### Missão

> *Ser um laboratório que proporciona um ambiente estimulante, visando maximizar o potencial dos alunos tanto como cientistas quanto como indivíduos.*[^1]

[^1]: *Esta frase foi retirada de um artigo do professor Uri Alon [@alon2009]. Poucas vezes em minha vida puder ler meus valores em uma frase de outra pessoa como esta vez.*

### Visão

De modo a guiar a criação e consolidação do laboratório proposto, apresento a visão para ele:

-   Excelência em Pesquisa Científica;

-   Integração com a Comunidade Acadêmica e Local;

-   Fomentar a Colaboração Internacional;

-   Formação de Novos Líderes em Pesquisa;

-   Inovação Contínua e Adaptação;

-   Liderança em Ética e Integridade Científica;

-   Impacto Duradouro na Formação Acadêmica;

-   Orgulho Institucional e Reconhecimento;

### Agradecimento especial

Gostaria de expressar minha sincera gratidão ao Prof. Dr. Juarez Lopes Ferreira da Silva, ilustre membro do Departamento de Físico-Química do Instituto de Química de São Carlos da Universidade de São Paulo, por sua generosidade em compartilhar publicamente seu memorial no ResearchGate. Embora ainda não tenhamos tido a oportunidade de nos conhecer pessoalmente, a iniciativa do professor de disponibilizar seu trabalho tem sido de imensa valia para minha trajetória acadêmica e profissional.

```{=typst}
#pagebreak()
```
## Dados pessoais {#sec-2}

**Nome Completo:** Marcel Rodrigues Ferreira.

**Nome Científico:** Marcel R. Ferreira

**Nome em Citações:** M.R.Ferreira.

**Data de Nascimento:** 02/05/1991.

**Estado Civil:** Deb Deb 💖.

**Local de Nascimento:** Itapetininga, São Paulo, Brasil.

**Nacionalidade:** Brasileira.

**Endereço Profissional:** Universidade Estadual Paulista "Júlio de Mesquita Filho", Faculdade de Medicina de Botucatu, Unidade de Pesquisa Experimental (UNIPEX). Av. Prof. Mário Rubens Guimarães Montenegro, s/n Bairro: Distrito de Rubião Júnior. Cep: 18.618-687 - Botucatu, SP

**Telefone Profissional:** (14) 3880-1749.

**E-mail:** [marcel.ferreira\@unesp.br](mailto:marcel.ferreira@unesp.br).

**CV Lattes:** <http://lattes.cnpq.br/5630742099737794>.

**ORCID:** <https://orcid.org/0000-0002-3445-0945>.

**Web of Science ResearcherID:** A-5830-2018

**Google Scholar:** <https://scholar.google.com.br/citations?user=lS42GYwAAAAJ&hl=pt-BR>

**Scopus**[^2]**:** <https://www.scopus.com/authid/detail.uri?authorId=56765071000>

[^2]: Na plataforma Scopus meu nome esta como Marcel Rodrigues Rodrigues Ferreira. Já foi solicitado mais de uma vez a correção, porém até a presente data não foi realizada.

**Website:** <http://marceelrf.netlify.app/>

**ResearchGate:** <https://www.researchgate.net/profile/Marcel-Rodrigues-Ferreira?ev=hdr_xprf.>

**Linkedin:** <https://www.linkedin.com/in/marceelrf/>

**GitHub:** <https://github.com/marceelrf>

```{=typst}
#pagebreak()
```
## Formação Acadêmica e Científica {#sec-3}

### Ensino Fundamental e Médio: 1998-2008

Minha trajetória educacional começou na cidade de Itapetininga, interior de São Paulo, onde tive a sorte de ser cercado por um ambiente familiar que valorizava a educação e o desenvolvimento integral desde cedo. Meus pais, pertencentes à classe média baixa, fizeram um esforço considerável para me matricular em instituições de ensino que pudessem proporcionar uma formação de qualidade, entendendo que a educação seria a base para minhas futuras conquistas.

O ensino fundamental foi realizado no Colégio Alpis, entre os anos de 1998 e 2005. Durante esse período, além do currículo escolar tradicional, meus pais incentivaram práticas esportivas, estudos de língua inglesa e artes, com aulas de violão, o que contribuiu significativamente para uma visão mais ampla e multidisciplinar do mundo.

Entre 2006 e 2008, cursei o ensino médio no Sistema Educacional Quintal (Objetivo). Essa etapa foi particularmente inspiradora, graças às aulas de laboratório de química, física e biologia que frequentava no período vespertino. Essas experiências práticas foram fundamentais para despertar meu interesse por uma carreira científica, mostrando-me a importância da experimentação e do conhecimento aplicado.

Ambas as escolas desempenharam um papel crucial na minha formação, reforçando a ideia de que uma educação abrangente e multidisciplinar é essencial para o desenvolvimento pessoal e profissional. Sou extremamente grato aos meus pais pelo sacrifício em custear escolas particulares, que, apesar dos desafios financeiros, sempre priorizaram meu aprendizado e crescimento.

### Graduação: 2011--2014

Após dois anos pessoalmente muito dificies, em 2011 entrei no curso de Bacharelado em Física Médica do Insituto de Biociências de Botucatu da Universidade Estadual Paulista "Júlio de Mesquita Filho" ([UNESP](https://www2.unesp.br/)). Durante os 4 anos de curso, tive acesso a uma formação multidisciplinar. Ainda nas primeiras semanas, ouvi a frase "aproveitem todos os espaços que a universidade pública lhes proporciona" e tomei-a como meu mantra. Participei de diversas atividades acadêmicas como: o cursinhos pré-vestibular Desafio e Eukaípia, empresa júnior Nucleon Jr, atlética, organização do Congresso de Física Aplicada a Medicina, monitorias, e iniciação cientifica.

Após enfrentar dois anos de desafios pessoais significativos, ingressei, em 2011, no curso de Bacharelado em Física Médica do Instituto de Biociências de Botucatu da Universidade Estadual Paulista "Júlio de Mesquita Filho" ([UNESP](https://www2.unesp.br/)). Ao longo dos quatro anos de graduação, tive a oportunidade de acessar uma formação profundamente multidisciplinar, que abrangeu desde os fundamentos da física até aplicações práticas na medicina.

Nas primeiras semanas de curso, uma orientação ressoou em minha mente como um mantra: "*aproveitem todos os espaços que a universidade pública lhes proporciona*". Inspirado por essa mensagem, participei ativamente de diversas atividades acadêmicas e extracurriculares, incluindo:

-   **Cursinhos pré-vestibular**: Contribuí como professor e monitor de matemática no [cursinho Desafio](https://www.fmb.unesp.br/#!/extensao/cursinho-desafio/) (2011) e como professor e coordenador de matemática no projeto Eukaípia [^3] (2012-2013), ambos voltados para a preparação de estudantes de baixa renda para o vestibular.

-   **Empresa júnior**: Fui membro da Nucleon Jr, onde adquiri experiência prática em consultoria e projetos relacionados à física médica.

-   **Atlética**: Fui membro ativo da Associação Atlética Acadêmica de Botucatu, como atleta e, posteriormente, como Diretor de Modalidade de Tênis de Mesa. Nessa função, tive a oportunidade de influenciar significativamente a prática do esporte, conduzindo a equipe a resultados expressivos em competições e incentivando um aumento no número de praticantes da modalidade.

-   **Organização de eventos**: Auxiliei na organização do Congresso de Física Aplicada à Medicina de 2014, uma experiência enriquecedora que me permitiu interagir com profissionais e pesquisadores renomados na área.

-   **Monitorias**: Atuei como monitor nas disciplinas de Física 3 para os cursos de Física Médica e de Fundamentos de Física do curso de Ciências Biomédicas, reforçando meu conhecimento e auxiliando colegas em suas jornadas acadêmicas.

-   **Iniciação científica**: Engajei-me em projetos de pesquisa, fundamentais para o desenvolvimento de meu pensamento crítico e habilidades científicas.

-   **Recepção universitária**: Nos anos de 2012 e 2013 participei da organização da recepção do calouros do Instituto de Biociências de Botucatu.

[^3]: O cursinho Eukaípia, do qual fui participante, foi renomeado em 2014 para Cursinho do IB e, posteriormente, em 2017, para [Cursinho Athena](https://www.ibb.unesp.br/#!/extensao/cursinhos-athena/) --- denominação que tive a honra de sugerir. Durante as etapas de meu mestrado e doutorado, não apenas continuei como professor, mas também assumi a função de coordenador de disciplina nesses projetos, contribuindo para a sua evolução e impacto na comunidade.

Tive a oportunidade de cursar diversas disciplinas durante os 4 anos de curso de Física Médica, abrangendo várias áreas do conhecimento, incluindo Humanas, Biológicas e, claro, Exatas. Essa diversidade de temas enriqueceu minha formação e proporcionou uma visão mais holística e integrada das ciências. Essa abordagem multidisciplinar foi essencial para minha formação, com destaque para as disciplinas de Linguagem de Programação, Bioquímica Básica, Biofísica Molecular e Física Computacional, que foram fundamentais para minha trajetória acadêmica e profissional. No terceiro ano, iniciei minha jornada científica sob a orientação do [Prof. Dr. Mario de Oliveira Neto](http://lattes.cnpq.br/8213371495151651), do Departamento de Física e Biofísica (atualmente Biofísica e Farmacologia), com uma bolsa PIBIC/PROPe[^4] via CNPq. Nesse período, mergulhei no estudo da estrutura de proteínas, utilizando dados de espalhamento de raios X a baixo ângulo (SAXS) e tive meu primeiro contato com bases de dados biológicas. Embora o projeto original, focado em proteínas relacionadas ao câncer bucal, não tenha avançado, desenvolvi outro sobre proteínas envolvidas na produção de etanol de segunda geração, que, embora não alinhasse diretamente com meu desejo de atuar no setor da saúde, proporcionou valiosos aprendizados. Durante quase dois anos, refinei minhas habilidades na extração de informações de bases de dados públicas, culminando na apresentação do trabalho no congresso de iniciação científica da UNESP, no qual fui classificado para a fase final do evento. Esse período resultou na participação em dois artigos científicos, publicados em 2015 [@Alvarez2015] e em 2022 [@Franco2022]. As principais informações estão resumidas a seguir:

[^4]: PIBIC: Programa Institucional de Bolsas de Iniciação Científica. PROPe: Pró-Reitoria de Pesquisa.

```{=typst}
#line(length: 50%, stroke: white)
```
**Curso:** Bacharelado em Física Médica.

**Instituição:** Instituto de Biociências de Botucatu, da Universidade Estadual Paulista "Júlio de Mesquita Filho".

**Local:** Campus Rubião Junior, Botucatu, São Paulo, Brasil.

**Monografia:** Espalhamento de raios-X a baixo ângulo aplicado a caracterização de enzimas celulolíticas com potencial na transformação enzimática da biomassa.

**Orientador**: Prof. Dr. José Mario de Oliveira Neto.

**Iniciação Científica**: 12 meses com bolsa fornecida pelo CNPq,Universidade Estadual Paulista "Júlio de Mesquita Filho".

### Mestrado: 2015--2017

No último ano de graduação tive a oportunidade de assistir uma palestra do [Prof. Dr. Willian Fernando Zambuzzi](http://lattes.cnpq.br/9087428606376572) sobre a utilização de mecanismos de transdução de sinais intracelulares com fator para a predição para o desenvolvimento de biomateriais. Fiquei impactado com essa perspectiva e quando ao final de sua apresentação ele declarou que procurava alunos de pósgraduação para orientar no [PPG de Biotecnologia](https://www.ibb.unesp.br/#!/ensino/pos-graduacao/programas-stricto-sensu/biotecnologia/) que teria suas primeiras turmas de mestrado e doutorado não hesitei em enviar um e-mail sobre a possibilidade de fazer mestrado sob sua orientação. Fiz parte da primeira geração de pós-graduandos no recém fundado Laboratório de Bioensaios e Dinâmica celular no departamento de Química e Bioquímica, e pude acompanhar, e trabalhar para a consolidação dela como um grupo de excelência em pesquisa. Meu projeto de mestrado visava utilizar mecanismos de transdução de sinais de células cultivadas diretamente sobre superfícies de biomateriais. Para isso, utilizamos o método de avaliação do quinoma por meio de microarranjo de peptídeos (PamChip®). Tive o privilégio de ter meu projeto financiado pela FAPESP (2015/03639-8) e vivi um período de muito aprendizado durante sua execução.

Durante a execução do projeto de mestrado, adquiri uma formação sólida em técnicas de cultivo celular, incluindo manutenção, expansão e experimentação com diferentes linhagens celulares, bem como a padronização de ensaios *in vitro* aplicados à avaliação da interação célula--biomaterial. Nesse contexto, tive contato e treinamento em técnicas laboratoriais amplamente utilizadas em pesquisa biomédica, como Western blotting para análise de proteínas e vias de sinalização, microscopia eletrônica de varredura (MEV) associada à espectroscopia de energia dispersiva de raios X (EDX) para caracterização de superfícies de biomateriais e de células em adesão, além de ensaios de citotoxicidade baseados em MTT, cristal violeta e vermelho neutro. Esse período foi fundamental para o desenvolvimento de uma compreensão aprofundada dos mecanismos de sinalização celular, com ênfase em vias reguladas por quinases e fosfatases, possibilitando a interpretação crítica das respostas celulares diante de diferentes superfícies e estímulos físico-químicos.

Paralelamente, o projeto demandou o tratamento e a análise de grandes volumes de dados oriundos de experimentos de alto rendimento, o que motivou meu primeiro contato sistemático com a programação em linguagem R. Nesse contexto, desenvolvi habilidades em bioestatística e análise de dados, aplicando métodos estatísticos apropriados à interpretação dos resultados experimentais e à visualização gráfica das informações obtidas. Esses aprendizados foram decisivos para a consolidação de uma abordagem quantitativa e integrada da pesquisa científica, influenciando de maneira permanente minha formação como pesquisador e servindo de base para as atividades desenvolvidas em etapas posteriores da carreira acadêmica.

Foi também durante o mestrado que despertei um interesse consistente pelo desenvolvimento e pela aplicação de métodos alternativos ao uso de animais em pesquisa, especialmente no contexto da avaliação de biomateriais médico-odontológicos. A utilização de modelos celulares e abordagens baseadas em mecanismos de sinalização intracelular mostrou-se uma estratégia robusta, ética e cientificamente informativa, direcionando de forma permanente minhas linhas de investigação posteriores.

Como resultado desse período de formação, o trabalho desenvolvido deu origem a um artigo científico diretamente relacionado à dissertação de mestrado [@ferreira2020], além de duas publicações adicionais, de caráter paralelo, construídas a partir de colaborações estabelecidas durante o projeto, com divisão de autoria entre os pesquisadores envolvidos [@bezerra2017, @Fernandes2018].

```{=typst}
#line(length: 50%, stroke: white)
```
**Instituição:** Universidade Estadual Paulista, Insituto de Biociências de Botucatu.

**Local:** Botucatu, São Paulo, Brasil.

**Título**: Mestre em Biotecnologia.

**Área:** Biotecnologia.

**Dissertação:** OsteoBLAST: Rotina computacional de análise molecular global aliada à biologia sistêmica e aplicada à produção de biomateriais.

**Orientador:** [Prof. Dr. Willian Fernando Zambuzzi](http://lattes.cnpq.br/9087428606376572)

**Data de defesa:** 24/02/2017

**Bolsa:** FAPESP (2015/03639-8)

### Doutorado: 2017-2023

Ao final do mestrado, eu percebia que, por mais que as premissas de nosso trabalho fossem importantes, havia claras limitações nas metodologias propostas. A primeira foi o uso de uma tecnologia fechada, como a PamChip®, exclusiva da empresa PamGene. Este fato, somado a empresa não ter atuação no Brasil, diminuía o potencial de escalabilidade da tecnologia por nós proposta.

Embora a avaliação da atividade de quinases possua um elevado valor no entendimento do fluxo de informação biológica, hoje tenho o entendimento que o uso de métodos baseados em transcriptoma, são uma solução melhor para nossa proposta uma vez que são métodos amplamente difundidos na comunidade científica. A segunda limitação se dava na falta de conhecimento em métodos de análise físico-química das superfícies dos biomateriais. Esta segunda limitação me fez propor um projeto de doutorado que envolvesse mais métodos de síntese e caracterização de biomateriais, no caso fosfatos de cálcio. Meu orientador concordou e sugeriu que buscássemos trabalhar com a modificação destas superfícies com fatores de crescimento através do uso de plasma-rico em plaquetas (PRP).

Ao longo do doutorado, aprofundei e ampliei significativamente minha formação metodológica e conceitual, incorporando abordagens experimentais e analíticas que supriram limitações identificadas ao final do mestrado. Um dos avanços centrais desse período foi a incorporação de métodos baseados em transcriptômica, incluindo análise de miRNAs, aprendizado adquirido em um curso de verão realizado na Universidade de São Paulo, campus de Ribeirão Preto. Paralelamente, desenvolvi competências no processamento de plasma rico em plaquetas (PRP) e na síntese de diferentes fosfatos de cálcio, como hidroxiapatita, monetita e fosfato tricálcico (TCP), bem como na caracterização desses biomateriais por técnicas físico-químicas consolidadas, incluindo FTIR, difração de raios X (DRX), análise termogravimétrica (TGA) e ICP-MS. Também aprofundei o uso de métodos de análise de expressão gênica relativa, fortalecendo a integração entre dados moleculares e propriedades dos biomateriais. Ao longo desse período, busquei continuamente a qualificação em análise de dados, tendo realizado mais de vinte cursos de curta duração em programação e análise estatística utilizando as linguagens R e Python, o que contribuiu de forma decisiva para minha autonomia analítica e capacidade de lidar com dados complexos.

A trajetória do doutorado, no entanto, não se deu sem desafios. Ao optar por permanecer em um programa de pós-graduação em estágio de consolidação, enfrentei inicialmente a ausência de bolsas de fomento, o que me levou a atuar como professor particular de matemática e física em Botucatu durante todo o ano de 2017 e início de 2018. Essa condição impactou o ritmo inicial do projeto, situação que começou a ser revertida com a aprovação da minha bolsa FAPESP em julho de 2018. Após um período de reorganização e normalização do cronograma experimental, um novo e inesperado desafio se impôs com a pandemia de COVID-19. O fechamento repentino do laboratório, aliado às restrições sanitárias, resultou em perdas experimentais significativas, incluindo experimentos de longa duração e grupos experimentais comprometidos por falhas em equipamentos, não prontamente detectadas devido à ausência de pessoal no laboratório. Apesar dos impactos científicos e emocionais desse período, considero que essa adversidade contribuiu para meu amadurecimento acadêmico, exigindo adaptações no projeto e na estrutura da tese, além de resiliência e capacidade de replanejamento.

Entre as principais conquistas do doutorado, destaco a aprovação da bolsa FAPESP, cuja avaliação foi fortemente impactada pela perspectiva de realização de um estágio de pesquisa no exterior (BEPE), previamente alinhado com o Prof. Dr. Paulo G. Coelho, da New York University (NYU). No contexto dessa colaboração, o Prof. Dr. Lukasz Witek, então colaborador do Prof. Paulo, esteve em Botucatu em 2018 para ministrar treinamento e disciplina, fortalecendo a interação entre os grupos. Posteriormente, considerando sua transição institucional, o Prof. Paulo sugeriu que o Prof. Dr. Lukasz Witek assumisse a supervisão do estágio BEPE. Assim, entre 01/04/2022 e 31/12/2022, realizei estágio no Departamento de Patobiologia Molecular da Faculdade de Odontologia da NYU, sob supervisão do Prof. Dr. Lukasz Witek. Nesse período, tive contato com métodos avançados de análise in vitro de biomateriais ósseos, desenvolvimento de tintas para impressão 3D voltadas à regeneração óssea, técnicas de reologia, além de atuar na coordenação dos experimentos de cultura celular do laboratório. Essa experiência resultou em uma publicação científica direta com o grupo anfitrião e proporcionou uma vivência intensa em um ambiente internacional de excelência em pesquisa.

Ao longo do doutorado, publiquei diversos trabalhos científicos, tanto como primeiro autor quanto como colaborador. Dentre eles, destaco o artigo "*Platelet microparticles load a repertory of miRNAs programmed to drive osteogenic phenotype*" [@ferreira2021], que compôs um dos capítulos da minha tese; o trabalho "*GSVA score reveals molecular signatures from transcriptomes for biomaterials comparison*" [@ferreira2020a], inicialmente concebido como um projeto paralelo e que se tornou o artigo com maior número de citações da minha produção; e o artigo "*Mesenchymal Stem Cell Differentiation Induced by Lyophilized PRP During Early Osteogenesis*" [@Ferreira2026], publicado em 2026, que representa o principal produto científico do doutorado.

Adicionalmente, esse período marcou o início da minha consolidação como pesquisador independente, com o estabelecimento de novas colaborações, incluindo parcerias com o Prof. Dr. Rodrigo Cardoso de Oliveira (USP Bauru) e com os Profs. Rodrigo Augusto Foganholi da Silva e Denise Carletto Andia (Universidade Paulista). Tive também a oportunidade de coorientar alunos de iniciação científica em conjunto com o Prof. Dr. Willian Fernando Zambuzzi, participando ativamente da formação de Guilherme Gazolla Santana (FAPESP 2019/09943-1), Júlia Ferreira de Moraes (FAPESP 2022/14363-7) e Matheus Amaral Silva, experiência fundamental para o desenvolvimento da minha identidade como orientador e mentor acadêmico.

```{=typst}
#line(length: 50%, stroke: white)
```
**Instituição:** Universidade Estadual Paulista, Insituto de Biociências de Botucatu.

**Local:** Botucatu, São Paulo, Brasil.

**Título**: Doutor em Biotecnologia.

**Área:** Biotecnologia.

**Dissertação:** Plasma-rico em plaquetas liofilizado associado à nanohidroxiapatita na performance celular e regeneração óssea.

**Orientador:** [Prof. Dr. Willian Fernando Zambuzzi](http://lattes.cnpq.br/9087428606376572)

**Data de defesa:** 20/01/2023

**Bolsa:** FAPESP (2018/05731-7)

**Internacionalização:** Universidade de Nova Iorque (NYU), supervisão do Prof. Dr. Lukasz Witek. BEPE: "Plasma rico em plaquetas e fabricação de aditivos como uma alternativa promissora para ajudar a desenvolver ossos verdadeiro". Bolsa: FAPESP(2021/14271-2).

```{=typst}
#pagebreak()
```
## Atuação Profissional {#sec-4}

### Pós-doutorados: 2023-Presente

Ao final do meu doutorado, eu percebi que para pôr em prática este projeto, eu precisava de uma maior base de programação para poder desenvolver esses métodos de análise. A implementação de modelos de machine learning me parecia algo fundamental para o sucesso desta proposta. Foi neste momento que vi a possibilidade de uma bolsa de pós-doutorado em um projeto sob supervisão do Dr. Erick da Cruz Castelli, o qual eu já acompanhava a anos como um grande pesquisador na área de bioinformática, com uma habilidade excepcional de desenvolvimento de programas. Desde maio de 2023 venho trabalhando em seu grupo em diversos projetos que ampliaram meu conhecimento na área de ciências ômicas, especialmente genômica, epigenômica e transcriptômica, além de um maior entendimento de ferramentas de programação como Linux, containers docker, ambientes conda, programação em nuvem, além de ter a oportunidade de atuar em projetos de machine learning. Considerando toda essa trajetória eu meu considero apto para coordenar este importante projeto.\

```{=typst}
#pagebreak()
```
## Atividades Didáticas e Formação de Recursos Humanos {#sec-5}

### Atividades de Monitoria

1.  Monitor na disciplina de Física III do Curso de Física Médica (Ano **2013**; Carga horária: 2). Responsável: [Prof. Dr. Joel Mesa Hormaza](http://lattes.cnpq.br/8949540199759267);
2.  Monitor na disciplina de Fundamentos da Física do Curso de Ciências Biomédicas (Ano **2013**; Carga horária: 1). Responsável: [Proj. Dr. Jose Luiz Rybarczyk Filho](http://lattes.cnpq.br/3740074012748153);

### Disciplinas Ministradas

#### Disciplinas de pós-graduação

1.  **GEN001631** - Sequenciamento de Terceira Geração com Oxford Nanopore: Princípios e Aplicações em Bioinformática (Carga horária [**30 horas**]{.underline}).
2.  **GEN001641** - Desenvolvimento de pacotes e aplicativos biológicos com R (Carga horária [**30 horas**]{.underline}).

### Orientações em Nível de Graduação

1.  [**Juliana Azevedo Amaral**](http://lattes.cnpq.br/0088184184301073). "*Desenvolvimento de um Aplicativo para Gestão Integrada de Dados de Bioinformática em Análises Forenses*". Início: 2025. Fim: **EM ANDAMENTO**. Iniciação científica (Graduando em Ciências Biomédicas);

### Coorientações em Nível de Graduação

1.  [**Guilherme Gazolla Santana**](http://lattes.cnpq.br/7752316236611770). Trabalho de conclusão de curso "*Assinaturas moleculares do transcriptoma de células tronco mesenquimais do tecido adiposo em diferenciação: um olhar especial para a inflamação*" \[[link](https://repositorio.unesp.br/entities/publication/dc22dfd9-290c-4a29-94fa-31fca0da4d67)\]. Início: 2019. Fim: 2023. Iniciação científica (Bacharel em Física Médica). FAPESP: 2019/09943-1. Orientador: [Prof. Dr. Willian Fernando Zambuzzi](http://lattes.cnpq.br/9087428606376572);
2.  [**Júlia Ferreira de Moraes**](http://lattes.cnpq.br/4834833217154689). Trabalho de conclusão de curso "*Construção e caracterização de um modelo de scaffolds ósseo á base de hidrogéis*" \[[link](https://repositorio.unesp.br/entities/publication/dbd6d766-312d-4a2c-8b90-347ca5023904)\]. Início: 2021. Fim: 2023. Iniciação científica (Bacharel em Física Médica). FAPESP: 2022/14363-7. Orientador: [Prof. Dr. Willian Fernando Zambuzzi](http://lattes.cnpq.br/9087428606376572);
3.  [**Matheus Amaral Silva**](http://lattes.cnpq.br/0212300912963206). Trabalho de conclusão de curso "*OsteoCLUST: clusterização da resposta à biomateriais ósseos*" \[[link](https://repositorio.unesp.br/entities/publication/53dcc731-3e00-4626-acd9-0ae1d45bb8b7)\]. Início: 2022. Fim: 2023. Iniciação científica (Bacharel em Física Médica). Orientador: [Prof. Dr. Willian Fernando Zambuzzi](http://lattes.cnpq.br/9087428606376572);
4.  **Isabela Lorente Kraetzer**. Iniciação científica "*Desenvolvimento de um Aplicativo para Visualização da Predição de Fenótipo e Ancestralidade com Base em Genótipos*". Início: 2025. Fim: **EM ANDAMENTO**. Orientador: Prof. Dr. Erick da Cruz Castelli;

### Orientações em Nível de Pós-graduação

Até o momento não existem orientações a serem reportadas.

### Coorientações em Nível de Pós-graduação

1.  [**Matheus Amaral Silva**](http://lattes.cnpq.br/0212300912963206). "*OsteoCLUST: framework para clusterização da resposta de biomateriais ósseos*" \[[link](https://repositorio.unesp.br/entities/publication/7f5dbc9f-d610-4ed2-bb56-ce3d92f40cb7)\]. Início: 2023. Fim: 2025. Mestrado em Biotecnologia (IBB/UNESP). Orientador: [Prof. Dr. Willian Fernando Zambuzzi](http://lattes.cnpq.br/9087428606376572);
2.  [**Júlia Ferreira de Moraes**](http://lattes.cnpq.br/4834833217154689). "*Construção de unidades biomiméticas à partir de plasma rico em plaquetas associado ao fluído caótico utilizando misturadores estáticos: perspectivas de novos processos biotecnológicos para regeneração do tecido ósseo.*". Início: 2024. Fim: **EM ANDAMENTO**. Mestrado em Biotecnologia (IBB/UNESP). FAPESP: 2023/14547-3. Orientador: [Prof. Dr. Willian Fernando Zambuzzi](http://lattes.cnpq.br/9087428606376572);

```{=typst}
#pagebreak()
```
## Atividades de Pesquisa {#sec-6}

### Linhas de Pesquisa

Ao longo de minha trajetória acadêmica, concentrei-me em explorar e aprofundar o conhecimento em áreas-chave da regeneração óssea e análise de dados genômicos. Atualmente, minhas principais linhas de pesquisa podem ser resumidas em cinco vertentes interconectadas:

1.  **Aspectos moleculares e epigenéticos da regeneração óssea**

    Investigação dos mecanismos moleculares, epigenéticos e de sinalização celular envolvidos na resposta de células osteogênicas e endoteliais a biomateriais, com ênfase em processos de adesão celular, remodelação da matriz extracelular, osteogênese e angiogênese.

2.  **Desenvolvimento de métodos computacionais e ferramentas para análise de biomateriais ósseos**

    Desenvolvimento de metodologias computacionais, softwares e pacotes em R voltados à análise integrada de dados transcriptômicos, espectrais e funcionais, visando a comparação, classificação e predição do desempenho biológico de biomateriais ósseos.

3.  **Análise de dados de sequenciamento de terceira geração e genômica funcional**

    Desenvolvimento e aplicação de pipelines analíticos para dados de sequenciamento de longa leitura, com foco em variantes estruturais, modificações epigenéticas e integração de dados ômicos, aplicados a estudos funcionais, forense, biomédicos e translacionais.

4.  **Métodos de identificação humana e fenotipagem forense baseados em DNA**

    Desenvolvimento e validação de abordagens computacionais e estatísticas para identificação humana, genotipagem e inferência fenotípica a partir de dados genômicos, incluindo aplicações em genética forense e populacional, com ênfase em dados de sequenciamento de nova e terceira geração.

5.  **Avaliação da osteoimunidade no desenvolvimento e na regeneração óssea**

    Investigação da interação entre o sistema imune e o tecido ósseo durante processos de desenvolvimento, reparo e regeneração, com foco na resposta inflamatória induzida por biomateriais, no papel de células imunes e mediadores inflamatórios, e na integração entre sinais imunológicos e vias osteogênicas.

### Rede de colaboração

A atuação em pesquisa desenvolvida ao longo da carreira tem sido fortemente sustentada por uma rede de colaborações interinstitucionais e, em alguns casos, internacionais, fundamentais para a consolidação e a ampliação das linhas de investigação. Essas parcerias têm possibilitado a integração de diferentes expertises, o desenvolvimento de projetos multidisciplinares, a coautoria de publicações científicas e a formação de recursos humanos, contribuindo de maneira consistente para a qualidade, o alcance e o impacto da produção científica. A seguir, são listados os principais colaboradores com os quais mantenho ou mantive projetos de pesquisa ativos.

```{=typst}
#line(length: 50%, stroke: white)
```
-   Prof. Dr. Willian Fernando Zambuzzi --- Instituto de Biociências de Botucatu, Universidade Estadual Paulista "Júlio de Mesquita Filho" (UNESP);

<!-- -->

-   Prof. Dr. Erick da Cruz Castelli --- Faculdade de Medicina de Botucatu, Universidade Estadual Paulista "Júlio de Mesquita Filho" (UNESP);

<!-- -->

-   Prof. Dr. Celso Teixeira Mendes Junior --- Faculdade de Filosofia, Ciências e Letras de Ribeirão Preto, Universidade de São Paulo (USP);

<!-- -->

-   Prof. Dra. Silviene Fabiana de Oliveira --- Instituto de Biologia, Universidade de Brasília (UnB);

<!-- -->

-   Prof. Dr. Luis Antonio Justulin Junior --- Instituto de Biociências de Botucatu, Universidade Estadual Paulista "Júlio de Mesquita Filho" (UNESP);

<!-- -->

-   Prof. Dr. Rodrigo Augusto Foganholi da Silva --- Universidade Paulista (UNIP);

<!-- -->

-   Prof. Dra. Denise Carletto Andia --- Universidade Paulista (UNIP);

<!-- -->

-   Prof. Dr. Lukasz Witek --- New York University (NYU), Estados Unidos;

<!-- -->

-   Dra. Flavia Amadeu de Oliveira --- Sanford Burnham Prebys Medical Discovery Institute, Estados Unidos;

<!-- -->

-   Prof. Dr. Miten Jain --- Northeastern University, Estados Unidos.

```{=typst}
#line(length: 50%, stroke: white)
```
### Auxílio de Pesquisa

Nesta seção são apresentados os auxílios de pesquisa dos quais participei como pesquisador integrante ou colaborador, em projetos financiados por agências de fomento nacionais e internacionais. Embora não figure como pesquisador responsável, minha atuação nesses projetos envolveu contribuições científicas diretas para o desenvolvimento das atividades de pesquisa, a execução experimental e analítica, a produção de resultados e publicações, bem como a formação de recursos humanos. A participação nesses auxílios foi fundamental para a consolidação das linhas de pesquisa desenvolvidas e para o fortalecimento de colaborações interinstitucionais.

1.  Genômica funcional em tecido epitelial de brasileiros miscigenados utilizando sequenciamento long-read Oxford Nanopore: análiseintegrada da diversidade genética e expressão gênica para a predição da pigmentação da pele e de idade epigenética

    Descrição: Descrição: Edital Universal CNPq. Vigência: 23/11/2023 a 22/11/2026. Processo 408084/2023-5. Auxílio financeiro: R\$207.500,00..

    Situação: Em andamento; Natureza: Pesquisa.

    Alunos envolvidos: Doutorado: (3) .

    Integrantes: Silviene Fabiana de Oliveira - Integrante / Celso Mendes Júnior - Coordenador / Erick da Cruz Castelli - Integrante / Marcel Rodrigues Ferreira - Integrante.

2.  Validação e desenvolvimento de painéis de fenotipagem forense e ancestralidade biogeográfica como ferramenta auxiliar na genética forense, em especial para a busca de pessoas desaparecidas no Brasil

    Descrição: Chamada CNPq/MCTI/FNDCT N 44/2024 - UNIVERSAL (Faixa A). Vigência: 2025 a 2028. Processo 409907/2025-1. Auxílio financeiro: R\$140.000,00..\
    Situação: Em andamento; Natureza: Pesquisa.\
    \
    Integrantes: Celso Teixeira Mendes Junior - Integrante / Aguinaldo Luiz Simões - Integrante / Silviene Fabiana de Oliveira - Coordenador / Thássia Mayra Telles Carratto - Integrante / Ronaldo Carneiro da Silva Junior - Integrante / Marcel Rodrigues Ferreira - Integrante / Bruno Trindade - Integrante / Diana Vilas Boas e Silva - Integrante.\
    Financiador(es): Conselho Nacional de Desenvolvimento Científico e Tecnológico - Auxílio financeiro.

### Publicações: Artigos Completos Aceitos para Publicação e Publicados em Periódicos Internacionais, Capítulos de Livros Publicados, e Trabalhos Completos Publicados em Anais de Congressos

A seguir, apresentam-se, em ordem cronológica de publicação, os artigos científicos completos publicados em periódicos internacionais, bem como capítulos de livros e trabalhos completos publicados em anais de congressos. Para cada produção, são informados: autores, título do trabalho, nome do periódico (ou livro/anais), volume, número, páginas e ano de publicação. O DOI é apresentado na forma de hiperlink, permitindo o acesso direto à versão online do artigo, e o PMID é informado quando disponível.

1.  Alvarez TM, Liberato MV, Cairo JP, Paixão DA, Campos BM, [**Ferreira MR**]{.underline}, Almeida RF, Pereira IO, Bernardes A, Ematsu GC, Chinaglia M, Polikarpov I, de Oliveira Neto M, Squina FM. *A Novel Member of GH16 Family Derived from Sugarcane Soil Metagenome*. Appl Biochem Biotechnol. 2015 Sep;177(2):304-17. doi: [10.1007/s12010-015-1743-7](https://www.doi.org/10.1007/s12010-015-1743-7). Epub 2015 Aug 5. PMID: 26242386.

2.  Bezerra F, [**Ferreira MR**]{.underline}, Fontes GN, da Costa Fernandes CJ, Andia DC, Cruz NC, da Silva RA, Zambuzzi WF. *Nano hydroxyapatite-blasted titanium surface affects pre-osteoblast morphology by modulating critical intracellular pathways*. Biotechnol Bioeng. 2017 Aug;114(8):1888-1898. doi: [10.1002/bit.26310](https://www.doi.org/10.1002/bit.26310). Epub 2017 Jun 7. PMID: 28401535.

3.  Fernandes CJC, Bezerra F, [**Ferreira MR**]{.underline}, Andrade AFC, Pinto TS, Zambuzzi WF. *Nano hydroxyapatite-blasted titanium surface creates a biointerface able to govern Src-dependent osteoblast metabolism as prerequisite to ECM remodeling*. Colloids Surf B Biointerfaces. 2018 Mar 1;163:321-328. doi: [10.1016/j.colsurfb.2017.12.049](https://www.doi.org/10.1016/j.colsurfb.2017.12.049). Epub 2017 Dec 28. PMID: 29329077.

4.  da Costa Fernandes CJ, [**Ferreira MR**]{.underline}, Bezerra FJB, Zambuzzi WF. *Zirconia stimulates ECM-remodeling as a prerequisite to pre-osteoblast adhesion/proliferation by possible interference with cellular anchorage*. J Mater Sci Mater Med. 2018 Mar 26;29(4):41. doi: [10.1007/s10856-018-6041-9](https://www.doi.org/10.1007/s10856-018-6041-9). PMID: 29582191.

5.  da Silva RA, de Camargo Andrade AF, da Silva Feltran G, Fernandes CJDC, de Assis RIF, [**Ferreira MR**]{.underline}, Andia DC, Zambuzzi WF. *The role of triiodothyronine hormone and mechanically-stressed endothelial cell paracrine signalling synergism in gene reprogramming during hBMSC-stimulated osteogenic phenotype in vitro*. Mol Cell Endocrinol. 2018 Dec 15;478:151-167. doi: [10.1016/j.mce.2018.08.008](https://www.doi.org/10.1016/j.mce.2018.08.008). Epub 2018 Aug 22. PMID: 30142372.

6.  da Silva Feltran G, da Costa Fernandes CJ, [**Rodrigues Ferreira M**]{.underline}, Kang HR, de Carvalho Bovolato AL, de Assis Golim M, Deffune E, Koh IHJ, Constantino VRL, Zambuzzi WF. *Sonic hedgehog drives layered double hydroxides-induced acute inflammatory landscape*. Colloids Surf B Biointerfaces. 2019 Feb 1;174:467-475. doi: [10.1016/j.colsurfb.2018.11.051](https://www.doi.org/10.1016/j.colsurfb.2018.11.051). Epub 2018 Nov 22. PMID: 30497008.

7.  Machado MIP, Gomes AM, [Rodrigues MF]{.underline}[^5] , Silva Pinto T, da Costa Fernandes CJ, Bezerra FJ, Zambuzzi WF. *Cobalt-chromium-enriched medium ameliorates shear-stressed endothelial cell performance*. J Trace Elem Med Biol. 2019 Jul;54:163-171. doi: [10.1016/j.jtemb.2019.04.012](https://www.doi.org/10.1016/j.jtemb.2019.04.012). Epub 2019 Apr 24. PMID: 31109607.

8.  da S Feltran G, Bezerra F, da Costa Fernandes CJ, [**Ferreira MR**]{.underline}, Zambuzzi WF. *Differential inflammatory landscape stimulus during titanium surfaces obtained osteogenic phenotype*. J Biomed Mater Res A. 2019 Aug;107(8):1597-1604. doi: [10.1002/jbm.a.36673](https://www.doi.org/10.1002/jbm.a.36673). Epub 2019 Apr 9. PMID: 30884166.

9.  da Silva RA, Fuhler GM, Janmaat VT, da C Fernandes CJ, da Silva Feltran G, Oliveira FA, Matos AA, Oliveira RC, [**Ferreira MR**]{.underline}, Zambuzzi WF, Peppelenbosch MP. *HOXA cluster gene expression during osteoblast differentiation involves epigenetic contro*l. Bone. 2019 Aug;125:74-86. doi: [10.1016/j.bone.2019.04.026](https://www.doi.org/10.1016/j.bone.2019.04.026). Epub 2019 May 1. PMID: 31054377.

10. da Silva RA, [**Ferreira MR**]{.underline}, Gomes AM, Zambuzzi WF. *LncRNA HOTAIR is a novel endothelial mechanosensitive gene*. J Cell Physiol. 2020 May;235(5):4631-4642. doi: [10.1002/jcp.29340](https://www.doi.org/10.1002/jcp.29340). Epub 2019 Oct 21. PMID: 31637716.

11. Gomes OP, Feltran GS, [**Ferreira MR**]{.underline}, Albano CS, Zambuzzi WF, Lisboa-Filho PN. *A novel BSA immobilizing manner on modified titanium surface ameliorates osteoblast performance*. Colloids Surf B Biointerfaces. 2020 Jun;190:110888. doi: [10.1016/j.colsurfb.2020.110888](https://www.doi.org/10.1016/j.colsurfb.2020.110888). Epub 2020 Feb 20. PMID: 32114272.

12. da Silva RA, da Silva Feltran G, [**Ferreira MR**]{.underline}, Wood PF, Bezerra F, Zambuzzi WF. *The Impact of Bioactive Surfaces in the Early Stages of Osseointegration: An \<i\>In Vitro\</i\> Comparative Study Evaluating the HAnano® and SLActive® Super Hydrophilic Surfaces*. Biomed Res Int. 2020 Sep 13;2020:3026893. doi: [10.1155/2020/3026893](https://www.doi.org/10.1155/2020/3026893). PMID: 33005686; PMCID: PMC7509554.

13. [**Ferreira MR**]{.underline}, Milani R, Rangel EC, Peppelenbosch M, Zambuzzi W. *OsteoBLAST: Computational Routine of Global Molecular Analysis Applied to Biomaterials Development*. Front Bioeng Biotechnol. 2020 Oct 8;8:565901. doi: [10.3389/fbioe.2020.565901](https://www.doi.org/10.3389/fbioe.2020.565901). PMID: 33117780; PMCID: PMC7578266.

14. Assis RIF, Feltran GDS, Silva MES, Palma ICDR, Rovai ES, Miranda TB, [**Ferreira MR**]{.underline}, Zambuzzi WF, Birbrair A, Andia DC, da Silva RA. *Non-coding RNAs repressive role in post-transcriptional processing of RUNX2 during the acquisition of the osteogenic phenotype of periodontal ligament mesenchymal stem cells*. Dev Biol. 2021 Feb;470:37-48. doi: [10.1016/j.ydbio.2020.10.012](https://www.doi.org/10.1016/j.ydbio.2020.10.012). Epub 2020 Nov 2. PMID: 33152274.

15. [**Ferreira MR**]{.underline}, Santos GA, Biagi CA, Silva Junior WA, Zambuzzi WF. *GSVA score reveals molecular signatures from transcriptomes for biomaterials comparison*. J Biomed Mater Res A. 2021 Jun;109(6):1004-1014. doi: [10.1002/jbm.a.37090](https://www.doi.org/10.1002/jbm.a.37090). Epub 2020 Sep 9. PMID: 32820608.

16. [**Ferreira MR**]{.underline}, Zambuzzi WF. *Platelet microparticles load a repertory of miRNAs programmed to drive osteogenic phenotype*. J Biomed Mater Res A. 2021 Aug;109(8):1502-1511. doi: [10.1002/jbm.a.37140](https://www.doi.org/10.1002/jbm.a.37140). Epub 2020 Dec 10. PMID: 33258548.

17. Pinto TS, Martins BR, [**Ferreira MR**]{.underline}, Bezerra F, Zambuzzi WF. *Nanohydroxyapatite-Blasted Bioactive Surface Drives Shear-Stressed Endothelial Cell Growth and Angiogenesis*. Biomed Res Int. 2022 Feb 23;2022:1433221. doi: [10.1155/2022/1433221](https://www.doi.org/10.1155/2022/1433221). PMID: 35252440; PMCID: PMC8890866.

18. Franco Cairo JPL, Mandelli F, Tramontina R, Cannella D, Paradisi A, Ciano L, [**Ferreira MR**]{.underline}, Liberato MV, Brenelli LB, Gonçalves TA, Rodrigues GN, Alvarez TM, Mofatto LS, Carazzolle MF, Pradella JGC, Paes Leme AF, Costa-Leonardo AM, Oliveira-Neto M, Damasio A, Davies GJ, Felby C, Walton PH, Squina FM. *Oxidative cleavage of polysaccharides by a termite-derived \<i\>superoxide dismutase\</i\> boosts the degradation of biomass by glycoside hydrolases*. Green Chem. 2022 May 12;24(12):4845-4858. doi: [10.1039/d1gc04519a](https://www.doi.org/10.1039/d1gc04519a). PMID: 35813357; PMCID: PMC9208272.

19. da C Fernandes CJ, da Silva RAF, de Almeida GS, [**Ferreira MR**]{.underline}, de Morais PB, Bezerra F, Zambuzzi WF. Epigenetic *Differences Arise in Endothelial Cells Responding to Cobalt-Chromium*. J Funct Biomater. 2023 Feb 26;14(3):127. doi: [10.3390/jfb14030127](https://www.doi.org/10.3390/jfb14030127). PMID: 36976051; PMCID: PMC10052026.

20. Fernandes CJDC, da Silva RAF, Wood PF, [**Ferreira MR**]{.underline}, de Almeida GS, de Moraes JF, Bezerra FJ, Zambuzzi WF. *Titanium-Enriched Medium Promotes Environment-Induced Epigenetic Machinery Changes in Human Endothelial Cells*. J Funct Biomater. 2023 Feb 27;14(3):131. doi: [10.3390/jfb14030131](https://www.doi.org/10.3390/jfb14030131). PMID: 36976055; PMCID: PMC10055987.

21. da Costa Fernandes CJ, [**Ferreira MR**]{.underline}, Zambuzzi WF. *Cyclopamine targeting hedgehog modulates nuclear control of the osteoblast activity*. Cells Dev. 2023 Jun;174:203836. doi: [10.1016/j.cdev.2023.203836](https://www.doi.org/10.1016/j.cdev.2023.203836). Epub 2023 Mar 25. PMID: 36972848.

22. Amadeu de Oliveira F, Tokuhara CK, Veeriah V, Domezi JP, Santesso MR, Cestari TM, Ventura TMO, Matos AA, Dionísio T, [**Ferreira MR**]{.underline}, Ortiz RC, Duarte MAH, Buzalaf MAR, Ponce JB, Sorgi CA, Faccioli LH, Buzalaf CP, de Oliveira RC. The *Multifarious Functions of Leukotrienes in Bone Metabolism*. J Bone Miner Res. 2023 Aug;38(8):1135-1153. doi: [10.1002/jbmr.4867](https://www.doi.org/10.1002/jbmr.4867). Epub 2023 Jun 29. PMID: 37314430.

23. Carvalho LB, Dos Santos Sanna PL, Dos Santos Afonso CC, Bondan EF, da Silva Feltran G, [**Ferreira MR**]{.underline}, Birbrair A, Andia DC, Latini A, Foganholi da Silva RA. *MicroRNA biogenesis machinery activation and lncRNA and REST overexpression as neuroprotective responses to fight inflammation in the hippocampus*. J Neuroimmunol. 2023 Sep 15;382:578149. doi: [10.1016/j.jneuroim.2023.578149](https://doi.org/10.1016/j.jneuroim.2023.578149). Epub 2023 Jul 18. PMID: 37481910.

24. Bergamo ETP, Balderrama ÍF, [**Ferreira MR**]{.underline}, Spielman R, Slavin BV, Torroni A, Tovar N, Nayak VV, Slavin BR, Coelho PG, Witek L. *Osteogenic differentiation and reconstruction of mandible defects using a novel resorbable membrane: An in vitro and in vivo experimental study*. J Biomed Mater Res B Appl Biomater. 2023 Nov;111(11):1966-1978. doi: [10.1002/jbm.b.35299](https://doi.org/10.1002/jbm.b.35299). Epub 2023 Jul 20. PMID: 37470190.

25. de Almeida GS, [**Ferreira MR**]{.underline}, da Costa Fernandes CJ, Suter LC, Carra MGJ, Correa DRN, Rangel EC, Saeki MJ, Zambuzzi WF. *Development of cobalt (Co)-doped monetites for bone regeneration*. J Biomed Mater Res B Appl Biomater. 2024 Jan;112(1):e35319. doi: [10.1002/jbm.b.35319](https://www.doi.org/10.1002/jbm.b.35319). Epub 2023 Aug 23. PMID: 37610175.

26. de Almeida GS, [**Ferreira MR**]{.underline}, Fernandes CC Jr, de Biagi CAO Jr, Silva WA Jr, Rangel EC, Lisboa-Filho PN, Zambuzzi WF. *Combination of in silico and cell culture strategies to predict biomaterial performance: Effects of sintering temperature on the biological properties of hydroxyapatite*. J Biomed Mater Res B Appl Biomater. 2024 Feb;112(2):e35389. doi: [10.1002/jbm.b.35389](https://www.doi.org/10.1002/jbm.b.35389). PMID: 38356168.

27. Lemes Dos Santos Sanna P, Bernardes Carvalho L, Cristina Dos Santos Afonso C, de Carvalho K, Aires R, Souza J, [**Rodrigues Ferreira M**]{.underline}, Birbrair A, Martha Bernardi M, Latini A, Foganholi da Silva RA. *Adora2A downregulation promotes caffeine neuroprotective effect against LPS-induced neuroinflammation in the hippocampus*. Brain Res. 2024 Jun 15;1833:148866. doi: [10.1016/j.brainres.2024.148866](https://www.doi.org/10.1016/j.brainres.2024.148866). Epub 2024 Mar 15. PMID: 38494098.

28. da Silva Feltran G, Augusto da Silva R, da Costa Fernandes CJ, [**Ferreira MR**]{.underline}, Dos Santos SAA, Justulin Junior LA, Del Valle Sosa L, Zambuzzi WF. *Vascular smooth muscle cells exhibit elevated hypoxia-inducible Factor-1α expression in human blood vessel organoids, influencing osteogenic performance*. Exp Cell Res. 2024 Jul 15;440(2):114136. doi: [10.1016/j.yexcr.2024.114136](https://www.doi.org/10.1016/j.yexcr.2024.114136). Epub 2024 Jun 22. PMID: 38909881.

29. Fernandes CJC, Silva RA, [**Ferreira MR**]{.underline}, Fuhler GM, Peppelenbosch MP, van der Eerden BC, Zambuzzi WF. *Vascular smooth muscle cell-derived exosomes promote osteoblast-to-osteocyte transition via β-catenin signaling*. Exp Cell Res. 2024 Sep 1;442(1):114211. doi: [10.1016/j.yexcr.2024.114211](https://www.doi.org/10.1016/j.yexcr.2024.114211). Epub 2024 Aug 14. PMID: 39147261.

30. Naia Fioretto M, Maciel FA, Barata LA, Ribeiro IT, Basso CBP, [**Ferreira MR**]{.underline}, Dos Santos SAA, Mattos R, Baptista HS, Portela LMF, Padilha PM, Felisbino SL, Scarano WR, Zambrano E, Justulin LA. *Impact of maternal protein restriction on the proteomic landscape of male rat lungs across the lifespan*. Mol Cell Endocrinol. 2024 Oct 1;592:112348. doi: [10.1016/j.mce.2024.112348](https://www.doi.org/10.1016/j.mce.2024.112348). Epub 2024 Aug 31. PMID: 39218056.

31. [**Ferreira MR**]{.underline}, Carratto TMT, Frontanilla TS, Bonadio RS, Jain M, de Oliveira SF, Castelli EC, Mendes-Junior CT. *Advances in forensic genetics: Exploring the potential of long read sequencing*. Forensic Sci Int Genet. 2025 Jan;74:103156. doi: [10.1016/j.fsigen.2024](https://www.doi.org/10.1016/j.fsigen.2024).103156. Epub 2024 Oct 10. PMID: 39427416.

32. L Urbano Pagan, M Gatto, [**MR Ferreira**]{.underline}, MJ Gomes, JPG Oliveira, GAF Mota, FC Damatto, LM Souza, ACC Santos, EA Rodrigues, PA Borim, DHS Campos, MP Okoshi, K Okoshi. *Effects of empagliflozin on myocardial transcriptome in rats with aortic stenosis-induced heart failure*. European Heart Volume 45, Issue Supplement_1, October 2024, ehae666.1829. doi: [10.1093/eurheartj/ehae6](https://doi.org/10.1093/eurheartj/ehae666.1829)

33. Castelli EC, Pereira RN, Paes GS, Andrade HS, [**Ferreira MR**]{.underline}, de Freitas Santos ÍS, Vince N, Pollock NR, Norman PJ, Meyer D. *kir-mapper: A Toolkit for Killer-Cell Immunoglobulin-Like Receptor (KIR) Genotyping From Short-Read Second-Generation Sequencing Data*. HLA. 2025 Mar;105(3):e70092. doi: [10.1111/tan.70092](https://www.doi.org/). PMID: 40095784; PMCID: PMC11927768.

34. Zambuzzi WF, [**Ferreira MR**]{.underline}. *Dynamic ion-releasing biomaterials actively shape the microenvironment to enhance healing*. J Trace Elem Med Biol. 2025 Jun;89:127657. doi: [10.1016/j.jtemb.2025.127657](https://www.doi.org/10.1016/j.jtemb.2025.127657). Epub 2025 Apr 17. PMID: 40250222.

35. Zambuzzi WF, [**Ferreira MR**]{.underline}, Wang Z, Peppelenbosch MP. *A Biochemical View on Intermittent Fasting's Effects on Human Physiology-Not Always a Beneficial Strategy*. Biology (Basel). 2025 Jun 9;14(6):669. doi: [10.3390/biology14060669](https://www.doi.org/10.3390/biology14060669). PMID: 40563920; PMCID: PMC12190167.

36. [**Ferreira MR**]{.underline}, Feltran GDS, Gomes AM, Vieira JCS, Santana GG, Silva MA, Santos EAAD, Zambuzzi WF. *Mesenchymal Stem Cell Differentiation Induced by Lyophilized PRP During Early Osteogenesis*. Cell Biol Int. 2026 Jan;50(1):e70101. doi: [10.1002/cbin.70101](https://www.doi.org/10.1002/cbin.70101). Epub 2025 Nov 13. PMID: 41230788.

37. C. J. C. Fernandes, R. A. Foganholi da Silva, [**M. R. Ferreira**]{.underline}, and W. F. Zambuzzi, "*Venous Endothelial Cells Promote Osteoblast Differentiation More Effectively Than Arterial Cells via TGF-β/BMP9 and Notch Pathway-Related Gene Expression*," *Cell Biochemistry and Function* 44 (2026): 1-14. <https://doi.org/10.1002/cbf.70160>.

[^5]: Houve um erro na submissão, resultando na inversão dos sobrenomes. Portanto, o nome correto é Marcel Rodrigues Ferreira. Caso queira confirmar a veracidade desse artigo, o professor Dr. Willian Zambuzzi ([w.zambuzzi\@unesp.br](mailto:w.zambuzzi@unesp.br)) pode ser consultado.

### Análise Estatística das Publicações

1.  Número de publicações: 37.

2.  Número de artigos completos em periódicos: 36.

3.  Número de citações: 632 (Google Scholar), 540 (ResearchGate), 502 (Scopus), 479 (ResearcherID).

4.  Média de citações: 18,06 (Google Scholar), 15,43 (ResearchGate), 14,34 (Scopus), 13,31 (ResearcherID).

5.  h-index: 14 (Google Scholar), 13 (ResearchGate), 13 (Scopus), 12 (ResearcherID).

### Contribuições Científicas

Uma das vertentes centrais da minha atuação científica tem sido o desenvolvimento de ferramentas computacionais voltadas à análise, integração e interpretação de dados biológicos complexos, com ênfase em transcriptômica, biomateriais e ciência de dados reprodutível. Essas iniciativas surgiram da necessidade de traduzir questões biológicas e experimentais em soluções metodológicas acessíveis, padronizadas e reutilizáveis pela comunidade científica.

Nesse contexto, desenvolvi e registrei o software **OsteoCLUST** -- Aplicativo para Análise e Comparação de Biomateriais Ósseos com Base em Dados Transcriptômicos (Processo nº BR512024004865-0), cuja titularidade pertence à Universidade Estadual Paulista "Júlio de Mesquita Filho". O **OsteoCLUST** integra rotinas estatísticas e visualizações interativas para a comparação global de assinaturas moleculares associadas à resposta celular a biomateriais, utilizando dados transcriptômicos. O aplicativo foi implementado utilizando as linguagens R, HTML, JavaScript e CSS, refletindo uma abordagem interdisciplinar entre análise de dados e desenvolvimento de interfaces amigáveis ao usuário.

Anteriormente, participei do desenvolvimento e registro do software **previewDeconv** -- um aplicativo para pré-visualização de bandas deconvoluídas (Processo nº BR512023000985-7), também com titularidade da UNESP. Esse aplicativo, implementado em C++, R e HTML, foi concebido para auxiliar na análise e interpretação de dados espectrais, contribuindo para a padronização de etapas analíticas em estudos físico-químicos e de biomateriais.

Além dos softwares registrados, sou autor do pacote **tidyspec** [@tidyspec], publicado no repositório oficial do [CRAN](https://cran.r-project.org/)[^6], voltado à organização, processamento e análise de dados espectrais no ambiente R, seguindo princípios do ecossistema tidyverse. Esse pacote tem sido utilizado tanto em minhas pesquisas quanto em atividades didáticas, contribuindo para a formação de estudantes em análise de dados reprodutível.

[^6]: O CRAN, ou *Comprehensive R Archive Network*, é um repositório online que armazena pacotes de software para a linguagem de programação R. Ele é mantido por uma comunidade global de desenvolvedores e usuários de R, e permite que os usuários acessem e baixem pacotes de software que expandem as funcionalidades básicas do R. O CRAN é essencial para o ecossistema R, pois facilita a distribuição de pacotes e garante que eles sejam de código aberto, documentados e testados.

```{=typst}
#line(length: 50%, stroke: white)
```
#### Aplicativo para Análise e Comparação de Biomateriais Ósseos com Base em Dados Transcriptômicos (OsteoCLUST) {.unnumbered}

**Processo Nº:** BR512024004865-0

**Título:** Aplicativo para Análise e Comparação de Biomateriais Ósseos com Base em Dados Transcriptômicos

**Data de criação:** 31/07/2024

**Titular(es):** UNIVERSIDADE ESTADUAL PAULISTA JULIO DE MESQUITA FILHO

**Autor(es):** MARCEL RODRIGUES FERREIRA; WILLIAN FERNANDO ZAMBUZZI; MATHEUS AMARAL SILVA

**Linguagem:** HTML; JAVA SCRIPT; CSS; R

**Campo de aplicação:** BL-01; BL-02; SD-09; SD-11

**Tipo de programa:** AP-01

**Algoritmo hash:** SHA-512

**Resumo digital hash:** cd598a23d0c6ff8bdd0135060116bc5066aed84dd6252cb47831bacf4656c3f8a90ae94c7513addd572c91c20aab4140e2 4465caa515da6e966d0baf742002a0

**Expedido em:** 17/12/2024

```{=typst}
#line(length: 50%)
```
#### previewDeconv: um aplicativo para pré-visualização de bandas deconvoluídas Data de criação {.unnumbered}

**Processo Nº:** BR512023000985-7

**Título:** previewDeconv: um aplicativo para pré-visualização de bandas deconvoluídas

**Data de criação:** 13/09/2021

**Titular(es):** UNIVERSIDADE ESTADUAL PAULISTA JULIO DE MESQUITA FILHO

**Autor(es):** WILLIAN FERANDO ZAMBUZZI; MARCEL RODRIGUES FERREIRA

**Linguagem:** C++; HTML; R

**Campo de aplicação:** FQ-01; FQ-06; FQ-14; FQ-17

**Tipo de programa:** AP-01

**Algoritmo hash:** SHA-512

**Resumo digital hash:**

58c79b6c8e6d67cfbccb7a4a357c1ae895a9d25b5eb310a512655f1a7fa46257f826b0fe75917085af0e322e31f00e855f8d ef4c642d0c8f260ddd051143ba9b

**Expedido em:** 18/04/2023

```{=typst}
#line(length: 50%)
```
#### Resumo: {.unnumbered}

-   Softwares registrados: *previewDeconv* e *OsteoCLUST* ;

-   Pacotes de R publicados no CRAN: *tidyspec* [@tidyspec];

-   Softwares sem registros publicados em artigos científicos: *kir-mapper* [@Castelli2025];

```{=typst}
#pagebreak()
```
## Atividades de Extensão e Serviços à Comunidade {#sec-7}

As atividades de extensão e os serviços prestados à comunidade constituem um eixo estruturante da minha trajetória acadêmica e profissional, estando presentes de forma contínua desde o início da formação universitária. Ao longo dos anos, tenho participado ativamente de iniciativas voltadas à democratização do acesso ao conhecimento, à formação educacional e científica de estudantes e à interação direta entre a universidade e a sociedade. Destacam-se, nesse contexto, os projetos de extensão relacionados a cursinhos pré-vestibulares e pré-universitários, nos quais atuei majoritariamente como responsável, evidenciando um compromisso duradouro com ações de impacto social e educacional.

Paralelamente, minha atuação em extensão também se manifesta na participação em bancas examinadoras, na organização de eventos científicos e acadêmicos, na oferta de cursos, seminários e palestras, bem como no exercício de atividades de assessoramento e avaliação científica para periódicos nacionais e internacionais. Conjuntamente, essas ações refletem uma compreensão ampliada do papel do docente universitário, que articula ensino, pesquisa e extensão, contribuindo não apenas para a formação acadêmica qualificada, mas também para o fortalecimento do vínculo entre a universidade, a comunidade científica e a sociedade em geral.

### Projetos de extensão

1.  **Cursinho Pré Universitário Atena**

    Situação: Concluído Natureza: Projeto de extensão. Integrantes: Marcel Rodrigues Ferreira (Responsável);

2.  **Cursinho Pré Vestibular do Instituto de Biociências de Botucatu** (2015 - 2017)

    Situação: Concluído Natureza: Projeto de extensão. Integrantes: [**Marcel Rodrigues Ferreira**]{.underline} (Responsável); ; Célio Junior da Costa Fernandes;

3.  **Nucleon JR** (2013 - 2014 )

    Descrição: Empresa junior dos alunos do curso de Física Médica do Instituto de Biociências de Botucatu/UNESP. Situação: Concluído Natureza: Projeto de extensão. Integrantes: [**Marcel Rodrigues Ferreira**]{.underline} (Responsável); ; Fernanda Nascimento Moura;

4.  **Cursinho CAVJ/IB** (2012-2013).

    Situação: Concluído Natureza: Projeto de extensão. Integrantes: [**Marcel Rodrigues Ferreira**]{.underline} (Responsável);

5.  **Cursinho Desafio** (2011-2011).

    Descrição: Cursinho pré vestibular destinado a estudantes de Escolas Públicas. Conta com a coordenação e participação de estudantes dos cursos da Unesp de Botucatu. Situação: Concluído Natureza: Projeto de extensão. Integrantes: [**Marcel Rodrigues Ferreira**]{.underline}; Raíssa Pierre Carvalho (Responsável)

### Participação em Bancas Examinadoras e Julgadoras

Sempre que solicitado, tenho participado na composição de bancas examinadoras de trabalho de conclusão de curso, qualificações de mestrado e doutorado, defesas de mestrado e doutorado, etc. Abaixo, estão listadas as participações em bancas examinadoras como membro titular das comissões:

1.  **06-02-2023** Membro da Banca Examinadora do TRABALHO DE CONCLUSÃO DE CURSO de MARIA GABRIELA JACHETO CARRA, discente do curso de Física Médica, Bacharelado;

2.  **09-03-2023** Membro da Banca Examinadora do TRABALHO DE CONCLUSÃO DE CURSO de ALLINE REGONATTI ARAUJO, discente do curso de Física Médica, Bacharelado;

3.  **30-08-2023** Membro da Comissão Examinadora da DEFESA DE TESE de ANDERSON MOREIRA GOMES, discente regular do Programa de Pós-Graduação em Biotecnologia, Curso de Doutorado;

4.  **31-10-2023** Membro da Banca Examinadora do TRABALHO DE CONCLUSÃO DE CURSO de CARLA CRISTINA ALBERTINI, discente do curso de Engenharia de Bioprocessos e Biotecnologia, Bacharelado;

5.  **31-10-2023** Membro da Banca Examinadora do TRABALHO DE CONCLUSÃO DE CURSO de PAULA BERTIN DE MORAIS, discente do curso de Engenharia de Bioprocessos e Biotecnologia, Bacharelado;

6.  **08-12-2023** Membro da Banca Examinadora do TRABALHO DE CONCLUSÃO DE CURSO de JÚLIA BUCCI, discente do curso de Física Médica, Bacharelado;

7.  **04-07-2024** Membro da Banca Examinadora do TRABALHO DE CONCLUSÃO DE CURSO de THAMIRES PRAZERES BARBOZA, discente do curso de Engenharia de Bioprocessos e Biotecnologia, Bacharelado;

8.  **30-10-2024** Membro da Banca Examinadora do TRABALHO DE CONCLUSÃO DE CURSO de CARLOS HENRIQUE SILVA SIMÕES, discente do curso de Engenharia de Bioprocessos e Biotecnologia, Bacharelado;

9.  **27-02-2025** Membro da Comissão Examinadora da DEFESA DE DISSERTAÇÃO de RENATO MATTOS, discente regular do Programa de Pós-Graduação em Biologia Geral e Aplicada, Curso de Mestrado Acadêmico;

10. **30-09-2025** Membro da Comissão Examinadora do Exame de QUALIFICAÇÃO de GABRIEL HENRIQUE CAXALI, discente regular do Programa de Pós-Graduação em Ciências Biológicas (Genética), Curso de Doutorado;

11. **04-11-2025** Membro da Comissão Examinadora do Exame de QUALIFICAÇÃO de MARIA LETICIA DE OLIVEIRA LYRA, discente regular do Programa de Pós-Graduação em Biologia Geral e Aplicada, Curso de Mestrado Acadêmico;

12. **19-11-2025** Membro da Comissão Examinadora da DEFESA DE DISSERTAÇÃO de MATHEUS RODRIGUES SAUDA, discente regular do Programa de Pós-Graduação em Ciências Biológicas (Genética), Curso de Mestrado Acadêmico;

13. **08-01-2026** Membro da Comissão Examinadora da DEFESA DE DISSERTAÇÃO de LUISA ANNIBAL BARATA, discente regular do Programa de Pós-Graduação em Biologia Geral e Aplicada, Curso de Mestrado Acadêmico;

### Cursos, Seminários e Palestras Ministradas

Esta seção reúne os cursos, seminários e palestras ministrados ao longo da trajetória acadêmica e profissional, em diferentes contextos institucionais e científicos. As atividades aqui descritas refletem a atuação na difusão do conhecimento, na formação de estudantes e profissionais, bem como na troca de experiências com a comunidade acadêmica e científica, abrangendo ações de caráter didático, técnico e científico, realizadas em âmbito presencial e remoto.

**Palestras:**

1.  FERREIRA, MR. *Inteligência Artificial e o Futuro da Pesquisa: Desafios e Oportunidades*, **2025**. Evento: IX Congresso de Pesquisa e Iniciação Científica - VI Congresso de Pós-graduação e III Encontro de Práticas Extensionistas da FAFIPE/FUNEPE, promovido pela Faculdade de Filosofia, Ciências e Letras de Penápolis (FAFIPE), mantida pela Fundação Educacional de Penápolis (FUNEPE); Modalidade: **Presencial**.

2.  FERREIRA, M. R. *Bioinformática: Perspectivas para Físicos Médicos*, **2024**. Evento: XVIII CONFIAM - Congresso de Física Aplicada à Medicina; Modalidade: **Presencial**.

3.  FERREIRA, M. R. *Biotecnologia forense: Bioinformática aplicada na identificação humana por DNA*, **2024**. Evento: I Workshop de Engenharia de Bioprocessos e Biotecnologia (WEBB); Modalidade: **Presencial**.

4.  FERREIRA, MR. *Desvendando os Segredos dos Dados Biológicos: O Poder da Bioinformática*, **2024**. Evento: Programa de Pós-Graduação em Biometria da Universidade Estadual Paulista "Júlio de Mesquita Filho" -- UNESP; Modalidade: **Presencial**.

5.  FERREIRA, MR. *Mesa-redonda: Internacionalização em Biotecnologia*, **2023**. Evento: VIII Workshop de Biotecnologia, organizado pelos alunos de Pós-graduação em Biotecnologia, da Universidade Estadual Paulista "Júlio de Mesquita Filho"; Modalidade: **Online**;

6.  FERREIRA, MR. *Reanálise de datasets - pipelines e serviços*, **2023**. Evento: Disicplina de Noções Básicas e Aplicações da Bioinformática, do Programa de Pós-graduação em Biologia Geral e Aplicada; Modalidade: **Presencial**.

7.  FERREIRA, MR. *Bioinformática*, **2022**. Evento: Disciplina de "Técnicas Especiais aplicadas à Pesquisa em Patologia" junto ao Programa de Pós-Graduação em Patologia da Faculdade de

    Medicina de Botucatu -- UNESP; Modalidade: **Online**.

8.  FERREIRA, M.R. *Física das radiações*, **2022**. Evento: Curso de Medicina Veterinária da Faculdade Galileu de Botucatu; Modalidade: **Online**.

**Cursos ministrados:**

1.  [**FERREIRA, M. R.**]{.underline}. *Acelerando sua análise de dados com tidyverse*, **2024**. Evento: XXI Workshop de Genética (Curso de curta duração ministrado).

2.  [**FERREIRA, Marcel Rodrigues**]{.underline}; RECALDE, T. F.; CASTELLI, E. C.; MENDES JUNIOR, C. T. Curso de Difusão - *Bioinformática aplicada à genética forense: análise de dados de sequenciamento de segunda e terceira geração,* **2024**. (Curso de curta duração ministrado)

3.  [**FERREIRA, M. R.**]{.underline}. *Desvendando os Segredos da Visualização de dados: ggplot2 para Iniciantes*, **2024**. Evento: XIII Congresso de Biociências (Congrebio). (Curso de curta duração ministrado)

4.  [**FERREIRA, M. R**]{.underline}.; MENDES JUNIOR, C. T.; CASTELLI, E. C.; RECALDE, T. F.. *Bioinformática aplicada à genética forense: análise de dados de sequenciamento de segunda e terceira geração*, **2023**. (Curso de curta duração ministrado)

### Organização de Eventos

1.  FERREIRA, M. R.. III Workbiotech: Workshop da Pós Graduação em Biotecnologia II Symposium on Cellular Dynamics: Building Insights and Breaking Boundaries., 2017. (Organização de evento)

2.  OLIVEIRA NETO, M.; FERREIRA, M. R.. II Workshop de Biotecnologia, 2016.

3.  FERREIRA, M. R.. MINICURSO DE LATEX, 2014.

4.  FERREIRA, M. R.. X CONFIAM - Congresso de Física Aplicada à Medicina, 2014.

5.  FERREIRA, M. R.. ANÁLISE DE DADOS COM PLANILHA ELETRÔNICA, 2013.

### Assessor Ad-hoc: Agências de Fomento, Instituições Acadêmicas, e Avaliação de Artigos para Periódicos Nacionais e Internacionais

**Avaliação de Artigos para Periódicos Nacionais e Internacionais:**

1.  European Journal of Medical Research - Desde 2025 (01 parecer);

2.  Cell Biology and Toxicology - Desde 2024 (02 pareceres);

3.  Scientific Reports - Desde 2024 (02 pareceres);

4.  Life Sciences - Desde 2023 (01 parecer);

5.  Frontiers in Bioengineering and Biotechnology - Desde 2023 (01 parecer);

6.  BMC Molecular and Cell Biology - Desde 2023 (01 parecer);

```{=typst}
#pagebreak()
```
## Atividades Administrativas {#sec-8}

```{=typst}
#pagebreak()
```
## Nomenclatura para Lista de Anexos {#sec-9}

## Considerações Finais {#sec-10}

```{=typst}
#pagebreak()
```
## Bibliografia

::: {#refs}
:::

## Anexos {.unnumbered}
